// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250613055428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Models.BetData", b =>
                {
                    b.Property<int>("BetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BetId"));

                    b.Property<int>("Bet0")
                        .HasColumnType("int");

                    b.Property<int>("Bet1")
                        .HasColumnType("int");

                    b.Property<int>("Bet10")
                        .HasColumnType("int");

                    b.Property<int>("Bet2")
                        .HasColumnType("int");

                    b.Property<int>("Bet3")
                        .HasColumnType("int");

                    b.Property<int>("Bet4")
                        .HasColumnType("int");

                    b.Property<int>("Bet5")
                        .HasColumnType("int");

                    b.Property<int>("Bet6")
                        .HasColumnType("int");

                    b.Property<int>("Bet7")
                        .HasColumnType("int");

                    b.Property<int>("Bet8")
                        .HasColumnType("int");

                    b.Property<int>("Bet9")
                        .HasColumnType("int");

                    b.Property<int>("BetTotal")
                        .HasColumnType("int");

                    b.Property<int>("DeleteStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrawTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WinAmount")
                        .HasColumnType("int");

                    b.Property<int?>("Winner")
                        .HasColumnType("int");

                    b.Property<int?>("XValue")
                        .HasColumnType("int");

                    b.HasKey("BetId");

                    b.ToTable("BetData");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GameSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Buffer")
                        .HasColumnType("int");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GameSetting");
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("DistributerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("DId");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<int?>("ReferId")
                        .HasColumnType("int")
                        .HasColumnName("ReferId");

                    b.Property<string>("ReferName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RetailerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("RId");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SuperAdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("SId");

                    b.Property<int>("SuperDistributerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SDId");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Balance = 2147483647,
                            DateTime = new DateTime(2025, 6, 13, 11, 24, 23, 376, DateTimeKind.Local).AddTicks(942),
                            DeleteStatus = 1,
                            DistributerId = 0,
                            Note = "Initial SuperAdmin User",
                            Password = "admin123",
                            Percentage = 0,
                            ReferName = "superadmin",
                            RetailerId = 0,
                            Role = "superadmin",
                            Status = 1,
                            SuperAdminId = 1,
                            SuperDistributerId = 0,
                            UniqueId = "123456",
                            Username = "superadmin"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.WinningNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrawTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Profit")
                        .HasColumnType("int");

                    b.Property<int>("TotalPlayed")
                        .HasColumnType("int");

                    b.Property<int>("TotalWin")
                        .HasColumnType("int");

                    b.Property<int>("WinMod")
                        .HasColumnType("int");

                    b.Property<int>("Winner")
                        .HasColumnType("int");

                    b.Property<int>("XValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WinningNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
